# permissions for end users to view networkprobers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkprober-viewer-role
rules:
- apiGroups:
  - probes.bigmikes.io
  resources:
  - networkprobers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - probes.bigmikes.io
  resources:
  - networkprobers/status
  verbs:
  - get
